# Generated by Django 3.0.7 on 2020-09-29 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groway', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contacto',
            old_name='ventas_liquidar_reteiva_clientes_regimen_comun',
            new_name='ventas_liquidar_reteiva_responsable_iva_regimen_comun',
        ),
        migrations.RenameField(
            model_name='contacto',
            old_name='ventas_liquidar_reteiva_clientes_regimen_simple',
            new_name='ventas_liquidar_reteiva_responsable_iva_regimen_simple',
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='cifra_total_en_palabras',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='factura_de_compra',
            name='cifra_total_en_palabras',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='factura_de_venta',
            name='autoreterenta',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=11, null=True),
        ),
        migrations.AddField(
            model_name='factura_de_venta',
            name='cifra_total_en_palabras',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='nota_credito',
            name='autoreterenta',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=11, null=True),
        ),
        migrations.AddField(
            model_name='nota_credito',
            name='cifra_total_en_palabras',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='nota_debito',
            name='autoreterenta',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=11, null=True),
        ),
        migrations.AddField(
            model_name='nota_debito',
            name='cifra_total_en_palabras',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='insumo',
            name='impuesto_consumo_compras',
            field=models.CharField(choices=[('1', '16.00'), ('2', '8.00'), ('3', '4.00'), ('4', 'Exento')], max_length=2),
        ),
        migrations.AlterField(
            model_name='insumo',
            name='iva_compras',
            field=models.CharField(choices=[('1', '19.00'), ('2', '5.00'), ('3', 'Excluido'), ('4', 'Exento')], max_length=2),
        ),
        migrations.AlterField(
            model_name='item',
            name='impuesto_consumo_ventas',
            field=models.CharField(choices=[('1', '16.00'), ('2', '8.00'), ('3', '4.00'), ('4', 'Exento')], max_length=2),
        ),
        migrations.AlterField(
            model_name='item',
            name='iva_ventas',
            field=models.CharField(choices=[('1', '19.00'), ('2', '5.00'), ('3', 'Excluido'), ('4', 'Exento')], max_length=2),
        ),
        migrations.AlterField(
            model_name='organizacion',
            name='tarifa_autoreterenta',
            field=models.CharField(blank=True, choices=[('1', 'Tarifa 0.4%'), ('2', 'Tarifa 0.8%'), ('3', 'Tarifa 1.6%')], max_length=2),
        ),
    ]
