# Generated by Django 3.0.7 on 2020-10-05 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groway', '0002_auto_20200929_0602'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacto',
            name='medio_de_pago',
            field=models.CharField(blank=True, choices=[('10', 'Efectivo'), ('20', 'Cheque'), ('41', 'Transferencia Bancaria'), ('42', 'Consignación Bancaria')], max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='contacto',
            name='terminos_de_pago',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='factura_de_venta',
            name='cufe',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='factura_de_venta',
            name='imagen_qr',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='medio_de_pago',
            field=models.CharField(blank=True, choices=[('10', 'Efectivo'), ('20', 'Cheque'), ('41', 'Transferencia Bancaria'), ('42', 'Consignación Bancaria')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='factura_de_venta',
            name='medio_de_pago',
            field=models.CharField(blank=True, choices=[('10', 'Efectivo'), ('20', 'Cheque'), ('41', 'Transferencia Bancaria'), ('42', 'Consignación Bancaria')], max_length=2, null=True),
        ),
    ]
