# Generated by Django 3.0.7 on 2020-06-18 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groway', '0002_factura_de_venta_pagada'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura_de_venta',
            name='fecha_pago',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
