# Generated by Django 3.0.7 on 2020-06-18 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groway', '0003_factura_de_venta_fecha_pago'),
    ]

    operations = [
        migrations.AddField(
            model_name='nota_credito',
            name='pagada',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='nota_debito',
            name='pagada',
            field=models.BooleanField(default=False),
        ),
    ]
