# Generated by Django 3.0.7 on 2020-06-18 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groway', '0004_auto_20200618_0018'),
    ]

    operations = [
        migrations.AddField(
            model_name='nota_credito',
            name='fecha_pago',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nota_debito',
            name='fecha_pago',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
