# Generated by Django 3.0.7 on 2020-06-19 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groway', '0005_auto_20200618_0049'),
    ]

    operations = [
        migrations.AddField(
            model_name='gastos_registro',
            name='numero_gasto',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='gastos_registro',
            name='concepto_gasto',
            field=models.CharField(choices=[('R', 'Pago de Alquiler'), ('S', 'Pago de Servicios'), ('P', 'Pago de Nómina'), ('O', 'Material de oficina'), ('U', 'Marketing y Publicidad'), ('M', 'Mantenimiento'), ('L', 'Servicios de Limpiesa'), ('A', 'Asesorías, servicios jurídicos y auditorías'), ('T', 'Transporte'), ('I', 'Impuestos')], max_length=1),
        ),
    ]
